"""
Diacritic normalization using parametrized conversion table.

This module loads a CSV conversion table (bnf_diacritic_conversions.csv) that
maps special characters to their OpenITI equivalents. The conversion can be
toggled on/off via config without code changes.

Key design:
- Parametrized via CSV file (easy to adjust without code)
- Handles the critical ayn (ʿ) bug: normalizes consistently instead of transliterating
- Maps diacritics to OpenITI equivalents where available (ǧ → gh, ḏ → dh, etc.)
- Strips long vowels (ā → a) per specification
- Falls back to removing unmapped special characters
"""

from pathlib import Path
from functools import lru_cache
import pandas as pd


def load_conversion_table(csv_path: str) -> tuple[dict, bool]:
    """
    Load diacritic conversion table from CSV using pandas.

    Handles Excel-saved CSVs (with BOM) gracefully.

    Returns:
        (conversions_dict, is_populated) where:
        - conversions_dict: {character: replacement} mapping
        - is_populated: True if any conversions are defined, False if all empty
    """
    conversions = {}
    has_conversions = False

    try:
        # pandas handles BOM and encoding issues automatically
        df = pd.read_csv(csv_path)

        for _, row in df.iterrows():
            char = row['character']
            equiv = str(row['openiti_equivalent']).strip() if pd.notna(row['openiti_equivalent']) else ''

            if char and equiv and equiv != 'nan':
                conversions[char] = equiv
                has_conversions = True
            # elif char and char != 'nan':
            #     # No mapping provided - will remove the character
            #     conversions[char] = ''

    except FileNotFoundError:
        print(f"Warning: Conversion table not found at {csv_path}")
        print(f"         Expected: outputs/bnf_survey/diacritic_conversions.csv")
        print(f"         Run: python utils/survey_bnf.py build")
        return {}, False

    return conversions, has_conversions


@lru_cache(maxsize=1)
def get_conversion_table() -> tuple[dict, bool]:
    """
    Load and cache the diacritic conversion table.

    Looks for: outputs/bnf_survey/diacritic_conversions.csv
    This file is generated by utils/survey_bnf.py build as part of Stage 3.

    Returns
    -------
    (conversions_dict, is_populated)
        - conversions_dict: {character: replacement} mapping
        - is_populated: True if conversions are defined, False if all empty
    """
    csv_path = Path(__file__).parent.parent / "outputs" / "bnf_survey" / "diacritic_conversions.csv"
    return load_conversion_table(str(csv_path))


def normalize_with_diacritics(text: str, use_table: bool = True, warn_once: dict = {}) -> str:
    """
    Normalize text using diacritic conversion table with Unicode decomposition fallback.

    Processing logic:
    - If character has a mapping in table: use the mapped value
    - If character is ASCII: keep as-is
    - If character is non-ASCII unmapped: apply Unicode decomposition (remove combining marks)

    Parameters
    ----------
    text : str
        Input text
    use_table : bool
        If True, use CSV conversion table. If False, apply Unicode decomposition only.

    Returns
    -------
    str
        Normalized text (lowercase, diacritics converted/decomposed)
    """
    if not text:
        return ""

    from matching.normalize import _decompose_and_strip_combining_marks

    conversions = {}
    is_populated = True

    if use_table:
        conversions, is_populated = get_conversion_table()
        # Warn once if table is not populated
        if not is_populated and 'warned' not in warn_once:
            print("WARNING: Conversion table has not been populated.")
            print("         Unmapped diacritics will be handled via Unicode decomposition.")
            warn_once['warned'] = True

    result = []
    for char in text:
        # Check if character has a mapping in the table
        if char in conversions:
            result.append(conversions[char])
        # ASCII characters - keep as-is
        elif ord(char) <= 127:
            result.append(char)
        # Arabic script - keep as-is (table is for Latin diacritics only)
        # Arabic block: U+0600 to U+06FF
        elif 0x0600 <= ord(char) <= 0x06FF:
            result.append(char)
        # Other non-ASCII unmapped: apply Unicode decomposition (e.g., Latin diacritics)
        else:
            decomposed = _decompose_and_strip_combining_marks(char)
            result.append(decomposed)

    # Convert to lowercase and clean up whitespace
    normalized = ''.join(result).lower().strip()
    # Remove excess whitespace
    normalized = ' '.join(normalized.split())

    return normalized
