"""
Transliteration normalization for fuzzy matching.

Two complementary normalization strategies are supported:

1. **Heavy Normalization (No Table Required)**
   - Uses only the critical C→ʿ OpenITI conversion
   - Relies on Unicode NFD decomposition + combining mark removal
   - Preserves base characters via decomposition (Š→s, ḥ→h, ī→i)
   - Cannot produce digraphs (Š→s not Š→sh, Ǧ→g not Ǧ→gh)
   - Tolerates phonetic variation through fuzzy matching (e.g., "sarif" ≈ "sharif")
   - Fallback when conversion table unavailable or incomplete
   - Best for: broad matching, robustness to unknown characters

2. **Table-Driven Conversion (Recommended)**
   - Uses parametrized diacritic_conversions.csv lookup table
   - Preserves phonetic information via digraph conversions (š→sh, ḏ→dh, Ǧ→gh)
   - Better match quality for Arabic manuscripts (maintains transliteration conventions)
   - Handles uppercase variants (Š, Ḥ, Ǧ) via table if populated
   - Requires maintaining diacritic_conversions.csv (generated by utils/survey_bnf.py)
   - Enabled via config.USE_DIACRITIC_CONVERSION_TABLE = True
   - Best for: accurate phonetic matching, OpenITI compliance

Main entry point: normalize_for_matching()
- Step 1: C→ʿ conversion (critical OpenITI ayn normalization)
- Step 2: Optionally apply conversion table (if enabled)
- Step 3: Heavy Unicode decomposition (final cleanup of combining marks)
"""

import re
import unicodedata


def _decompose_and_strip_combining_marks(text: str) -> str:
    """
    Unicode decomposition: NFD normalize and remove combining marks.

    Separates base characters from diacritical marks via NFD decomposition,
    removes the marks (Unicode category Mn), and recomposes to NFC.
    This is the core of heavy diacritic normalization.

    Examples:
    - é (U+00E9) → e + combining acute → e
    - Š (U+0160) → S + combining caron → S
    - ī (U+012B) → i + combining macron → i
    - Preserves ayn (ʿ, U+02BF) which is category Lm (Modifier Letter), not Mn

    Parameters
    ----------
    text : str
        Text to decompose

    Returns
    -------
    str
        Text with combining marks removed, base characters preserved
    """
    if not text:
        return ""

    text = unicodedata.normalize("NFD", text)
    text = "".join(c for c in text if unicodedata.category(c) != "Mn")
    text = unicodedata.normalize("NFC", text)
    return text


def normalize_transliteration(text: str) -> str:
    """
    Heavy diacritic normalization via Unicode decomposition (no table needed).

    Strips diacritical marks by decomposing to base letters. Preserves all base
    characters; combines with conversion table for digraph mapping.

    Pipeline:
    1. Convert backtick ` to ʿ (BetaCode alternative for ayn)
    2. NFD decompose (separate base chars from combining marks)
    3. Remove combining diacritical marks (Unicode category Mn = Mark, nonspacing)
    4. NFC recompose
    5. Lowercase and normalize whitespace (hyphens → spaces)

    **Preservation via Decomposition:**
    - Š (U+0160) + caron → S + combining caron → remove caron → S → s
    - ḥ (U+1E25) + dot → h + combining dot → remove dot → h
    - ī (U+012B) + macron → i + combining macron → remove macron → i
    - ʿ (U+02BF) ayn → Lm (modifier, NOT Mn) → preserved

    **Result:** Characters preserved but phonetic distinction lost for diacritics
    (Š→s not sh, Ǧ→g not gh). Table-driven strategy handles digraph conversion.
    """
    if not text:
        return ""

    # 1. Convert backtick to ʿ (BetaCode ayn representation)
    # Backticks are an alternate way to write ayn; normalize them
    text = text.replace("`", "ʿ")

    # 2. Heavy Unicode decomposition: remove all combining diacritical marks
    # Uses shared helper function that handles NFD → remove Mn → NFC
    text = _decompose_and_strip_combining_marks(text)

    # 3. Lowercase for case-insensitive matching
    text = text.lower()

    # 4. Normalize whitespace and hyphens
    # Replace hyphens with spaces (so "al-Qahira" becomes "al qahira")
    text = re.sub(r"-+", " ", text)
    # Collapse multiple spaces into one
    text = re.sub(r"\s+", " ", text)
    # Strip leading/trailing whitespace
    text = text.strip()

    return text


def _apply_openiti_conversions(text: str, is_openiti: bool = False) -> str:
    """
    OpenITI-specific conversions (only applied to OpenITI data, not BNF).

    Parameters
    ----------
    text : str
        Input text
    is_openiti : bool, default False
        If True, apply C→ʿ conversion (OpenITI URIs use C as ayn placeholder).
        If False, skip C→ʿ (BNF data uses standard Latin script).

    Conversions applied only when is_openiti=True:
    - C, c → ʿ (unify ayn variants used in OpenITI URI encoding)

    Rationale:
    - 'C' as ayn placeholder is OpenITI-specific convention
    - BNF data uses standard Latin (C in "Catalogue" should NOT become ʿ)
    - This ensures normalized forms are comparable when both sides converted
    - All other diacritics handled downstream by decomposition or table
    """
    if is_openiti:
        conversions = {
            "C": "ʿ",      # ayn (OpenITI URI convention)
            "c": "ʿ",      # ayn (lowercase variant)
        }
        for char, replacement in conversions.items():
            text = text.replace(char, replacement)

    # Always remove hamza (common to both)
    text = text.replace("ʾ", "")

    return text


def normalize_for_matching(text: str, split_camelcase: bool = False, is_openiti: bool = False, skip_table: bool = False) -> str:
    """
    Main entry point for normalization. Routes through two strategies based on config.

    **Strategy 1: Heavy Normalization** — Config: USE_DIACRITIC_CONVERSION_TABLE = False
    - Uses optional C→ʿ OpenITI conversion (only if is_openiti=True)
    - Preserves base characters via NFD decomposition + combining mark removal
    - Output: Š→s, ḥ→h, ī→i (loses digraphs but preserves character structure)
    - Example: "Šarīf" → "sarif" (character preserved, phonetic variation via fuzzy match)
    - No table required, fallback when table unavailable
    - Trade-off: Some phonetic loss vs complete robustness

    **Strategy 2: Table-Driven** — Config: USE_DIACRITIC_CONVERSION_TABLE = True
    - Uses optional C→ʿ conversion + diacritic_conversions.csv table + Unicode decomposition
    - Table maps diacritics to phonetic equivalents (š→sh, ḥ→h, ḏ→dh, Ǧ→gh)
    - Output: Š→sh, Ǧ→gh, uppercase variants handled via table
    - Recommended for best phonetic accuracy in Arabic manuscript matching
    - Requires populated diacritic_conversions.csv (from utils/survey_bnf.py)
    - Trade-off: Better accuracy vs table maintenance requirement

    **Normalization Pipeline:**

    0a. Strip OpenITI date prefixes (only if is_openiti=True)
        - Remove all 4-digit sequences (e.g., "0685IbnKamal" → "IbnKamal")
        - Dates are metadata, not matching content
    0b. Split camelCase (only for OpenITI URIs like IbnKhayyat; False for regular text)
    1. Apply C→ʿ conversion (only if is_openiti=True; OpenITI convention, not BNF)
    2. [Optional] Apply table (if USE_DIACRITIC_CONVERSION_TABLE = True AND skip_table=False)
    3. Heavy Unicode decomposition (normalize_transliteration)
       - NFD decomposition + combining mark removal (category Mn)

    Parameters
    ----------
    text : str
        Text to normalize
    split_camelcase : bool, default False
        If True, split camelCase (e.g., "IbnKhayyat" → "Ibn Khayyat").
        Only use for OpenITI URIs; keep False for regular names/titles.
    is_openiti : bool, default False
        If True, apply C→ʿ conversion (OpenITI uses C as ayn placeholder in URIs).
        If False, keep standard Latin C (e.g., "Catalogue" stays as "catalogue").
        Set to True for OpenITI author/title URIs, False for BNF data.
    skip_table : bool, default False
        If True, skip the diacritic conversion table even if enabled.
        Use for OpenITI data normalization (table is for BNF→OpenITI conversion, not OpenITI normalization).

    This function is used throughout the matching pipeline (AuthorMatcher,
    TitleMatcher, etc.) on both BNF and OpenITI data with appropriate is_openiti flag.
    """
    # Import here to avoid circular dependency
    from matching.config import USE_DIACRITIC_CONVERSION_TABLE

    # Step 0a: Strip OpenITI date prefixes (4-digit sequences like "0685IbnKamal" → "IbnKamal")
    # Only for OpenITI data where dates are metadata, not content
    if is_openiti:
        text = re.sub(r"\d{4}", "", text)

    # Step 0b: Split camelCase only if requested (e.g., "IbnKhayyat" → "Ibn Khayyat")
    if split_camelcase:
        text = re.sub(r"([a-z])([A-Z])", r"\1 \2", text)

    # Step 1: Apply OpenITI-specific conversions (only if is_openiti=True)
    # C→ʿ is OpenITI convention; BNF data should not have this applied
    text = _apply_openiti_conversions(text, is_openiti=is_openiti)

    # Step 2: Apply parametrized diacritic table (optional)
    # User can specify additional conversions in outputs/bnf_survey/diacritic_conversions.csv
    if USE_DIACRITIC_CONVERSION_TABLE and not skip_table:
        from matching.normalize_diacritics import normalize_with_diacritics
        text = normalize_with_diacritics(text, use_table=True)

    # Step 3: Heavy Unicode normalization (handles remaining diacritics)
    # NFD decomposition + removal of combining marks (category Mn)
    # This is the final fallback for any diacritics not handled in steps 1-2
    return normalize_transliteration(text)


if __name__ == "__main__":
    # Quick test
    test_cases = [
        ("Kitab al-Tabari", "kitab al tabari"),
        ("Kitab al-Ṭabarī", "kitab al tabari"),
        ("ʿAbd al-Rahman", "ayn abd al rahman"),
        ("Cabd al-Rahman", "ayn abd al rahman"),
        ("AL-TABARI", "al tabari"),
        ("Anwār al-tanzīl", "anwar al tanzil"),
    ]

    for original, expected in test_cases:
        result = normalize_transliteration(original)
        status = "OK" if result == expected else "MISMATCH"
        print(f"{status}: {repr(original):30} -> {repr(result):30} (expected {repr(expected)})")
