"""
Diacritic normalization using parametrized conversion table.

This module loads a CSV conversion table (bnf_diacritic_conversions.csv) that
maps special characters to their OpenITI equivalents. The conversion can be
toggled on/off via config without code changes.

Key design:
- Parametrized via CSV file (easy to adjust without code)
- Handles the critical ayn (ʿ) bug: normalizes consistently instead of transliterating
- Maps diacritics to OpenITI equivalents where available (ǧ → gh, ḏ → dh, etc.)
- Strips long vowels (ā → a) per specification
- Falls back to removing unmapped special characters
"""

import csv
from pathlib import Path
from functools import lru_cache


def load_conversion_table(csv_path: str) -> tuple[dict, bool]:
    """
    Load diacritic conversion table from CSV.

    Returns:
        (conversions_dict, is_populated) where:
        - conversions_dict: {character: replacement} mapping
        - is_populated: True if any conversions are defined, False if all empty
    """
    conversions = {}
    has_conversions = False

    try:
        with open(csv_path, encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                char = row['character']
                equiv = row['openiti_equivalent'].strip()

                if char and equiv:
                    conversions[char] = equiv
                    has_conversions = True
                elif char:
                    # No mapping provided - will remove the character
                    conversions[char] = ''

    except FileNotFoundError:
        print(f"Warning: Conversion table not found at {csv_path}")
        print(f"         Expected: outputs/bnf_survey/diacritic_conversions.csv")
        print(f"         Run: python utils/survey_bnf.py build")
        return {}, False

    return conversions, has_conversions


@lru_cache(maxsize=1)
def get_conversion_table() -> tuple[dict, bool]:
    """
    Load and cache the diacritic conversion table.

    Looks for: outputs/bnf_survey/diacritic_conversions.csv
    This file is generated by utils/survey_bnf.py build as part of Stage 3.

    Returns
    -------
    (conversions_dict, is_populated)
        - conversions_dict: {character: replacement} mapping
        - is_populated: True if conversions are defined, False if all empty
    """
    csv_path = Path(__file__).parent.parent / "outputs" / "bnf_survey" / "diacritic_conversions.csv"
    return load_conversion_table(str(csv_path))


def normalize_with_diacritics(text: str, use_table: bool = True, warn_once: dict = {}) -> str:
    """
    Normalize text using diacritic conversion table.

    Parameters
    ----------
    text : str
        Input text
    use_table : bool
        If True, use CSV conversion table. If False, just remove all non-ASCII.

    Returns
    -------
    str
        Normalized text (lowercase, diacritics converted/removed)
    """
    if not text:
        return ""

    conversions = {}
    is_populated = True

    if use_table:
        conversions, is_populated = get_conversion_table()
        # Warn once if table is not populated
        if not is_populated and 'warned' not in warn_once:
            print("WARNING: Conversion table has not been populated.")
            print("         All non-standard Latin characters will be normalised to their standard variants.")
            warn_once['warned'] = True

    result = []
    for char in text:
        # Check if character has a mapping
        if char in conversions:
            result.append(conversions[char])
        # ASCII characters and spaces - keep as-is
        elif ord(char) <= 127:
            result.append(char)
        # Unmapped non-ASCII - remove it
        else:
            pass

    # Convert to lowercase and clean up whitespace
    normalized = ''.join(result).lower().strip()
    # Remove excess whitespace
    normalized = ' '.join(normalized.split())

    return normalized
